import Replicate from 'replicate';

export type VeoImageInput = string; // URL or data URI (data:image/...;base64,...)

export type RunVeoI2VParams = {
  /**
   * REQUIRED. Flux/Persona reference image URL (or base64 data URI).
   * This image is the first frame; Veo animates these exact pixels.
   * Do NOT call without it — falling back to text-to-video destroys persona identity (e.g. bravesage535).
   */
  image_url: VeoImageInput;
  /**
   * Text prompt for the video. Must align with the image: describe what is shown (e.g. if the image
   * shows a punch, the prompt must say "The character delivers the punch"). Ensures the video is a
   * direct animation of the reference image.
   */
  prompt: string;
  /** Replicate model id, e.g. "google/veo-3.1". */
  model?: string;
};

const defaultModel = 'google/veo-3.1';

/**
 * Run Veo 3.1 (or override model) in Image-to-Video mode only.
 *
 * CRITICAL: The Flux/Persona image MUST be passed as the reference image. The video is a direct
 * animation of that image's pixels, preserving face and clothes. There is no fallback to text-to-video
 * for persona content — missing image_url throws.
 *
 * Prompt alignment: The text prompt must match the visual context of the image (e.g. image shows a
 * punch → prompt says "The character delivers the punch").
 */
export async function runVeoImageToVideo(params: RunVeoI2VParams): Promise<unknown> {
  const { image_url, prompt, model = defaultModel } = params;

  const imageValue =
    image_url != null ? String(image_url).trim() : '';
  const missing = !imageValue || imageValue.length === 0;

  if (missing) {
    throw new Error(
      'Veo Image-to-Video requires image_url (Flux/Persona reference image). ' +
      'Do NOT fallback to text-to-video for Persona content — it destroys character identity (e.g. bravesage535). ' +
      'The video must be a direct animation of the specific pixels generated by Flux.'
    );
  }

  console.log('[VEO I2V] image_url (Flux/Persona reference):', imageValue.slice(0, 120) + (imageValue.length > 120 ? '...' : ''));

  const replicate = new Replicate({
    auth: process.env.REPLICATE_API_TOKEN,
  });

  const modelId = (model || process.env.REPLICATE_VEO_MODEL || defaultModel) as `${string}/${string}` | `${string}/${string}:${string}`;

  // google/veo-3.1: reference image MUST be passed as image (I2V). Video = animation of these pixels.
  const input: Record<string, unknown> = {
    prompt,
    image: imageValue,
  };

  return await replicate.run(modelId, { input });
}
